# Colors (Solarized Dark Patched)

# Default colors
[colors.primary]
background = '#031219'
foreground = '#708284'

# Normal colors
[colors.normal]
black   = '#002831'
red     = '#d11c24'
green   = '#738a05'
yellow  = '#a57706'
blue    = '#2176c7'
magenta = '#c61c6f'
cyan    = '#259286'
white   = '#eae3cb'

# Bright colors
[colors.bright]
black   = '#475b62'
red     = '#bd3613'
green   = '#475b62'
yellow  = '#536870'
blue    = '#708284'
magenta = '#5956ba'
cyan    = '#819090'
white   = '#fcf4dc'
